### PR TITLE
fix: add auto-renew check for negative values 

### LINKED ISSUE #18763: fix: add auto-renew check for negative values

### PR DESCRIPTION
**Pull request by vtronkov**
**Description**:
- Adding a check for the auto-renew period to verify that the value is positive
- Adding additional HAPI tests to verify cases from the TCK document

**Related issue(s)**:

Fixes #18763

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by ibankov — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java [hunk 1]
```diff
@@ -1047,4 +1047,49 @@ final Stream<DynamicTest> tokenUpdateReduceExpiry() {
...
+                tokenCreate("token")
+                        .tokenType(NON_FUNGIBLE_UNIQUE)
+                        .initialSupply(0)
+                        .adminKey("adminKey")
+                        .supplyKey("supplyKey"),
+                tokenUpdate("token")
+                        .autoRenewAccount("supplyKey")
+                        .autoRenewPeriod(Long.MIN_VALUE)
+                        .hasKnownStatus(INVALID_RENEWAL_PERIOD));
+    }
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java:1065]: Since the next test is checking for `autoRenewPeriod(-1)`, this test doesn't seem necessary.

**Review by mhess-swl — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java (hunk 1 above)
Comment (vtronkov) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java:1065]: The reason I'm adding explicitly -1 and `Long.MIN_VALUE` is because we have special cases where `Long.MIN_VALUE` has a different behaviour than any other negative value. With this test, I'm ensuring that is not the case.
