### PR TITLE
fix: Should reject a FILE_UPDATE to 0.0.123 with an invalid throttle definition

### LINKED ISSUE #13295: Should reject a `FILE_UPDATE` to `0.0.123` with an invalid throttle definition (whether 1-way or N-way splits)
### Description

Updated `0.0.123` with a set of throttle definitions whose 1-way split overflowed a `long`, i.e.,
```
2024-05-14 16:33:26.792 ERROR 785  ThrottleAccumulator - When constructing bucket 'ThroughputLimits' from state: NODE_CAPACITY_NOT_SUFFICIENT_FOR_OPERATION :: Bucket ThroughputLimits contains an unsatisfiable milliOpsPerSec with 1 nodes!
```
But this resolved to `SUCCESS` and resulted in the backend `TOKEN_MINT` throttle having no assigned bucket.

As a result **all** contract operations doing child transactions were throttled at `commit()`.

### Steps to reproduce

As above.

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.49.7

### Operating system

None

### PR DESCRIPTION
**Pull request by vtronkov**
**Description**:
- Add validation to check if the throttle group's milliOpsPerSec least common multiple is overflowing on FILE_UPDATE to 0.0.123

**Related issue(s)**:

Fixes #13295

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleParser.java [hunk 1]
```diff
@@ -118,4 +125,28 @@ private void checkForRepeatedOperations(ThrottleDefinitions throttleDefinitions)
...
+     *
+     * @param throttleDefinitions The throttle definitions to validate.
+     * @throws IllegalArgumentException If scaled capacity calculation overflows.
+     */
+    private void validateLeastCommonMultipleDoesNotOverflow(ThrottleDefinitions throttleDefinitions) {
+        for (var bucket : throttleDefinitions.throttleBuckets()) {
+            var lcm = leastCommonMultiple(bucket.throttleGroups());
+            final var unscaledCapacity = lcm * NTPS_PER_MTPS * CAPACITY_UNITS_PER_NANO_TXN / 1_000;
+            if (productWouldOverflow(unscaledCapacity, bucket.burstPeriodMs())) {
+                throw new IllegalArgumentException("Scaled bucket capacity calculation outside numeric range");
```
Comment (vtronkov) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleParser.java:140]: Should I create a custom Exception to throw here so I can catch it on `DispatchProcessor`?

Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleParser.java:140]: Hmm agreed, would make sense throw `new HandleException(THROTTLE_GROUP_LCM_OVERFLOW)` afaict.

Comment (vtronkov) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleParser.java:140]: Fixed 👍

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleParser.java [hunk 2]
```diff
@@ -118,4 +126,28 @@ private void checkForRepeatedOperations(ThrottleDefinitions throttleDefinitions)
...
+
+    /**
+     * Validates that scaled bucket capacity calculations, involving LCM and burst periods, don't overflow.
+     *
+     * @param throttleDefinitions The throttle definitions to validate.
+     * @throws IllegalArgumentException If scaled capacity calculation overflows.
+     */
+    private void validateLeastCommonMultipleDoesNotOverflow(ThrottleDefinitions throttleDefinitions) {
+        for (var bucket : throttleDefinitions.throttleBuckets()) {
+            var lcm = leastCommonMultiple(bucket.throttleGroups());
```
Comment (tinker-michaelj) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleParser.java:138]: For completeness, I think we should wrap this in a `try`/`catch (ArithmeticException)` and translate to the same `HandleException` in the `catch`.

Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleParser.java:138]: (I.e., wrap this entire method in a `try`/`catch` so that if **any** part of the calculation throws `ArithmeticException`, we catch it...not just the final multiplication by `burstPeriod`.)

Comment (vtronkov) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleParser.java]: Good catch, fixed 👍

**Review by tinker-michaelj — APPROVED** [review]
LGTM, tyvm @vtronkov !
