### PR TITLE
fix: Revert `hookDispatch` permissions, add characterizing tests

### LINKED ISSUE #21414: (0.67) Revert `HookDispatch` permissions
At some point a local test change was pushed that switched `HookDispatch` permissions from `0-0` to `0-*`. We should revert this and add:
- [x] Unit tests confirming all internal tx types have `0-0` permissions; and,
- [x] `@HapiTest`s confirming no internal tx body can be submitted through HAPI.

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #21414 
 - Also adds a missing `ApiPermissionConfig` entry for `NodeStakeUpdate`, so we can apply a single consistent policy for all internal tx types if we want to tune behavior for superuser payer accounts in future.

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/LeakyCryptoTestsSuite.java [hunk 1]
```diff
@@ -382,6 +404,74 @@ final Stream<DynamicTest> cannotExceedAllowancesTransactionLimit() {
...
+                                (spec, b) ->
+                                        b.setHistoryProofVote(HistoryProofVoteTransactionBody.getDefaultInstance()))
+                        .payingWith(CIVILIAN_PAYER)
+                        .hasPrecheck(BUSY),
+                explicit(
+                                CrsPublication,
+                                (spec, b) -> b.setCrsPublication(CrsPublicationTransactionBody.getDefaultInstance()))
+                        .payingWith(CIVILIAN_PAYER)
+                        .hasPrecheck(BUSY),
+                explicit(HookDispatch, (spec, b) -> b.setHookDispatch(HookDispatchTransactionBody.getDefaultInstance()))
```
Comment (Neeharika-Sompalli) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/LeakyCryptoTestsSuite.java:465]: Since we have not changed `throttles.json`, without the permissions change it still fails with `BUSY` on main.

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM! Thanks @tinker-michaelj

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/LeakyCryptoTestsSuite.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/LeakyCryptoTestsSuite.java:465]: True, true.
