### PR TITLE
fix: Fix the Otter Reconnect Test

### LINKED ISSUE #20627: Fix failing Otter Reconnect Test
The `ReconnectTest` is failing after the reconnect synchronization is complete with this stack trace:

```
025-08-14 13:23:58.213 [<reconnect: reconnect-controller>] [RECONNECT] INFO  com.swirlds.platform.reconnect.ReconnectController - receiving signed state failed 
org.hiero.base.exceptions.ReferenceCountException: can not reserve node that has already been destroyed
	at com.swirlds.common.utility.AbstractReservable.lambda$static$0(AbstractReservable.java:23)
	at java.base/java.util.concurrent.atomic.AtomicInteger.updateAndGet(AtomicInteger.java:281)
	at com.swirlds.common.utility.AbstractReservable.reserve(AbstractReservable.java:59)
	at com.swirlds.platform.state.signed.SignedState.<init>(SignedState.java:191)
	at com.swirlds.platform.reconnect.ReconnectLearner.reconnect(ReconnectLearner.java:211)
	at com.swirlds.platform.reconnect.ReconnectLearner.execute(ReconnectLearner.java:159)
	at com.swirlds.platform.reconnect.ReconnectSyncHelper.reconnectLearner(ReconnectSyncHelper.java:109)
	at com.swirlds.platform.reconnect.ReconnectSyncHelper.receiveSignedState(ReconnectSyncHelper.java:78)
	at com.swirlds.platform.reconnect.ReconnectController.executeReconnect(ReconnectController.java:110)
	at com.swirlds.platform.reconnect.ReconnectController.run(ReconnectController.java:91)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### PR DESCRIPTION
**Pull request by poulok**
This PR fixes the Otter Reconnect test, but also downgrades the level of the log reporting occurrences of coin rounds and the log reporting when a marker file tries to be written but fails because the file already exists. These are needed to allow otter tests to pass since the frequency of coin rounds in otter tests is so frequent.

Fixes #20627

### CODE REVIEW

File: platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/ReconnectTest.java [hunk 1]
```diff
@@ -99,7 +97,8 @@ void testSimpleNodeDeathReconnect(final TestEnvironment env) {
 
         assertThat(nodeToReconnect.newReconnectResult()).hasNoFailedReconnects().hasExactSuccessfulReconnects(1);
 
-        assertThat(network.newConsensusResults()).haveEqualCommonRounds();
+        assertThat(network.newConsensusResults().suppressingNode(nodeToReconnect))
+                .haveEqualCommonRounds();
```
Comment (lpetrovic05) [inline platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/ReconnectTest.java:101]: should the node that reconnects have also have equal common rounds?

Comment (poulok) [reply platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/ReconnectTest.java:101]: This method checks needs a little refactoring I think. The current implementation expects nodes to not have any gaps in its consensus rounds, which of course a node that reconnects will have. I am considering ways to improve this. Maybe with a new assertion.

Comment (poulok) [reply platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/test/ReconnectTest.java:101]: I created a ticket for this https://github.com/hiero-ledger/hiero-consensus-node/issues/20650
