### PR TITLE
fix: Fix batch transaction fees

### LINKED ISSUE #19093: Fix fee calculation for batch transactions
Fix the `ChildFeeContextImpl` to consider number of signature verifications if the child dispatch type is `BATCH`

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fixes #19093 

- Fixes batch transaction fees for inner transactions. Currently we were ignoring number of signatures while charging fees. Changed to use the [number of signatures](https://github.com/hiero-ledger/hiero-consensus-node/blob/db000043aa48d87c457806f3c26c447f728578bb/hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/ChildFeeContextImpl.java#L83) validated in `ChildFeeContext`
- Used [correct number of signatures verified](https://github.com/hiero-ledger/hiero-consensus-node/blob/db000043aa48d87c457806f3c26c447f728578bb/hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/DefaultKeyVerifier.java#L122) to charge fee, instead of the `legacyVpt` used for mono-service compatibility. 
- Only use the [inner preHandleResults](https://github.com/hiero-ledger/hiero-consensus-node/blob/db000043aa48d87c457806f3c26c447f728578bb/hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchHandleContext.java#L371) for `BATCH_INNER` transaction category, so we don't use wrong preHandleResults for preceding transactions.
- Change [dispatch options for atomic batch](https://github.com/hiero-ledger/hiero-consensus-node/blob/db000043aa48d87c457806f3c26c447f728578bb/hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/DispatchOptions.java#L361) to fail if inner transaction signatures are not verified.

### CODE REVIEW

**Review by tinker-michaelj — DISMISSED** [review]
LGTM, tyvm @Neeharika-Sompalli !

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/ChildFeeContextImpl.java [hunk 1]
```diff
@@ -33,6 +34,12 @@ public class ChildFeeContextImpl implements FeeContext {
     private final Authorizer authorizer;
     private final ReadableStoreFactory storeFactory;
     private final Instant consensusNow;
+    // The verifier is non-null only for batch inner transactions.
+    // Since all other child transactions have no signatures to verify, the verifier is no needed.
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/ChildFeeContextImpl.java:38]: Is this always true, that all other child transactions never have signatures to verify? At the very least, I thought we would need to verify signatures for child scheduled transactions

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java [hunk 2]
```diff
@@ -69,6 +72,42 @@
...
+                createTopic("topic")
+                        .adminKeyName("adminKey")
+                        .feeScheduleKeyName("feeScheduleKey")
+                        .withConsensusCustomFee(fixedConsensusHbarFee(ONE_HBAR, "collector")),
+                usableTxnIdNamed("innerTxnId").payerId("alice"),
+                usableTxnIdNamed("innerTxnId2").payerId("bob"),
+                atomicBatch(innerTxn1, innerTxn2).payingWith("batchOperator").via("batchTxn"),
+                validateChargedUsd("batchTxn", BASE_FEE_BATCH_TRANSACTION),
+                validateInnerTxnChargedUsd("innerTxnId", "batchTxn", BASE_FEE_HBAR_CRYPTO_TRANSFER, 5),
+                validateInnerTxnChargedUsd("innerTxnId2", "batchTxn", BASE_FEE_SUBMIT_MESSAGE_CUSTOM_FEE, 5));
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java:109]: Do we not also want to check separate sigs here?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/ChildFeeContextImpl.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/ChildFeeContextImpl.java:38]: All other synthetic child transactions don't have any signatures to verify. For the scheduled transactions we sign the top level ScheduleSign transaction and not the child transaction.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java (hunk 2 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java:112]: You mean add more signatures and verify the price @mhess-swl ?

Comment (mhess-swl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip551/AtomicBatchTest.java:112]: Nevermind, I'm thinking of something that is probably outside the scope of this test. 👍

**Review by mhess-swl — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/RecordCreationSuite.java [hunk 3]
```diff
@@ -130,26 +136,17 @@ final Stream<DynamicTest> submittingNodeChargedNetworkFeeForLackOfDueDiligence()
...
-                        .logged()),
-                sourcing(() -> getAccountBalance(FOR_ACCOUNT_STAKING_REWARDS)
-                        .hasTinyBars(changeFromSnapshot(
-                                STAKING_REWARD1, (long) (+feeObs.get().networkFee() * 0.1)))
-                        .logged()),
-                sourcing(() -> getAccountBalance(FOR_ACCOUNT_NODE_REWARD)
-                        .hasTinyBars(changeFromSnapshot(
-                                NODE_REWARD1, (long) (+feeObs.get().networkFee() * 0.1)))
-                        .logged()),
+                // validate node is charged
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/RecordCreationSuite.java:139]: Is it not important to check these balances anymore?

**Review by mhess-swl — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/RecordCreationSuite.java (hunk 3 above)
Comment (mhess-swl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/RecordCreationSuite.java:139]: Got it, thanks!

**Review by mhess-swl — APPROVED** [review]
LGTM! Thanks @Neeharika-Sompalli! 🙂
