### PR TITLE
fix: Add missing validation in ThrottleAccumulator #21052

### LINKED ISSUE #21052: Fix missing validation in `ThrottleAccumulator`
Currently we are not checking if the `ScheduleCreateTransactionBody ` has a scheduled transaction body in it. This causes a NPE in `ThrottleAccumulator`.

```
2025-09-12 10:24:36.339 ERROR 92   IngestWorkflowImpl - Possibly CATASTROPHIC failure while running the ingest workflow
java.lang.NullPointerException: Field scheduledTransactionBody is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:259)
	at com.hedera.hapi.node.scheduled.ScheduleCreateTransactionBody.scheduledTransactionBodyOrThrow(ScheduleCreateTransactionBody.java:607)
	at com.hedera.node.app.throttle.ThrottleAccumulator.shouldThrottleScheduleCreate(ThrottleAccumulator.java:500)
	at com.hedera.node.app.throttle.ThrottleAccumulator.shouldThrottleTxn(ThrottleAccumulator.java:468)
	at com.hedera.node.app.throttle.ThrottleAccumulator.checkAndEnforceThrottle(ThrottleAccumulator.java:188)
	at com.hedera.node.app.throttle.SynchronizedThrottleAccumulator.shouldThrottle(SynchronizedThrottleAccumulator.java:59)
	at com.hedera.node.app.workflows.ingest.IngestChecker.checkThrottles(IngestChecker.java:344)
	at com.hedera.node.app.workflows.ingest.IngestChecker.runAllChecks(IngestChecker.java:286)
	at com.hedera.node.app.workflows.ingest.IngestChecker.runAllChecks(IngestChecker.java:235)
	at com.hedera.node.app.workflows.ingest.IngestWorkflowImpl.submitTransaction(IngestWorkflowImpl.java:75)
```

**Solution:** 

Add a precheck validation if `ScheduleCreateTransactionBody` has a scheduled transaction body or throttle if there is no scheduled transaction body
```
  if(!op.hasScheduledTransactionBody()){
          // throttle the transaction, if it is not valid
            return true;
        }
```

### PR DESCRIPTION
**Pull request by aderevets**
**Description**:

This PR enhances the throttle system by adding validation for malformed transactions to prevent busy waiting on clients. Key changes include:

  - New ThrottleResult class: Refactored throttle methods to return a ThrottleResult object instead of boolean, containing both throttling decision and validation error information
  - Transaction validation: Added validation for required fields in SCHEDULE_CREATE, TOKEN_MINT, and ETHEREUM_TRANSACTION transaction types to catch malformed transactions early
  - Improved error handling: Validation errors now throw PreCheckException with INVALID_TRANSACTION response code, preventing malformed transactions from proceeding
  - Updated call sites: Modified AppThrottleFactory, NetworkUtilizationManagerImpl, and IngestChecker to handle the new ThrottleResult return type
  - Comprehensive tests: Added test coverage for malformed transaction scenarios

  The changes ensure that invalid transactions are rejected immediately during throttling rather than allowing them to proceed and potentially cause client-side busy waiting.

**Related issue(s)**:

Fixes #21052 
**Notes for reviewer**:

**Checklist**
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java [hunk 1]
```diff
@@ -484,6 +491,45 @@ yield shouldThrottleEthTxn(
...
+     * @throws HandleException if validation fails for malformed transactions
+     */
+    private void validateTransactionBody(
+            @NonNull final TransactionBody txnBody, @NonNull final HederaFunctionality function) {
+        try {
+            switch (function) {
+                case SCHEDULE_CREATE -> {
+                    final var scheduleCreate = txnBody.scheduleCreateOrThrow();
+                    if (!scheduleCreate.hasScheduledTransactionBody()) {
+                        throw new HandleException(ResponseCodeEnum.INVALID_SCHEDULE_ID);
```
Comment (derektriley) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java]: Throw PreCheckException here and INVALID_TRANSACTION

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleResult.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+package com.hedera.node.app.throttle;
+
+import com.hedera.hapi.node.base.ResponseCodeEnum;
+import edu.umd.cs.findbugs.annotations.Nullable;
+
+/**
+ * Represents the result of a throttle check operation, encapsulating whether the transaction
+ * should be throttled, any validation errors, and gas throttling status.
+ */
+public class ThrottleResult {
```
Comment (derektriley) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleResult.java]: Perhaps make this a record

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java [hunk 3]
```diff
@@ -167,31 +171,37 @@ public ThrottleAccumulator(
...
         resetLastAllowedUse();
         lastTxnWasGasThrottled = false;
-        if (shouldThrottleTxn(false, txnInfo, now, state, throttleUsages)) {
+        try {
+            if (shouldThrottleTxn(false, txnInfo, now, state, throttleUsages)) {
+                reclaimLastAllowedUse();
+                if (lastTxnWasGasThrottled) {
+                    return ThrottleResult.gasThrottled();
+                }
+                return ThrottleResult.throttled();
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java:198]: Why are these lines here ? 🤔

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java:198]: Ah makes sense..

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java [hunk 4]
```diff
@@ -484,6 +496,48 @@ yield shouldThrottleEthTxn(
...
+                    throw new PreCheckException(ResponseCodeEnum.INVALID_TRANSACTION);
+                }
+            }
+            case TOKEN_MINT -> {
+                if (!txnBody.hasTokenMint()) {
+                    throw new PreCheckException(ResponseCodeEnum.INVALID_TRANSACTION);
+                }
+                final var tokenMint = txnBody.tokenMint();
+                if (!tokenMint.hasToken()) {
+                    throw new PreCheckException(ResponseCodeEnum.INVALID_TRANSACTION);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java]: I think all these should return `INVALID_TRANSACTION_BODY`, since we could parse the transaction body from transaction.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java [hunk 5]
```diff
@@ -342,8 +343,11 @@ private void checkThrottles(
         final var hederaConfig = configuration.getConfigData(HederaConfig.class);
         final var hooksConfig = configuration.getConfigData(HooksConfig.class);
         assertThrottlingPreconditions(txInfo, hederaConfig, hooksConfig);
-        if (hederaConfig.ingestThrottleEnabled()
-                && synchronizedThrottleAccumulator.shouldThrottle(txInfo, state, throttleUsages)) {
+        ThrottleResult throttleResult = synchronizedThrottleAccumulator.shouldThrottle(txInfo, state, throttleUsages);
+        if (throttleResult.hasValidationError()) {
+            throw new PreCheckException(throttleResult.validationError());
+        }
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java]: This code should be under `hederaConfig.ingestThrottleEnabled()` this condition.

**Review by Neeharika-Sompalli — COMMENTED** [review]
Overall Looks great! Thanks @aderevets! Had two comments

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java (hunk 4 above)
Comment (aderevets) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java]: Thx I changed to INVALID_TRANSACTION_BODY

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM! Thanks @aderevets

**Review by Neeharika-Sompalli — APPROVED** [review]
