### PR TITLE
fix: Decouple hapiTestToken

### LINKED ISSUE #18955: Decouple `hapiTestToken` from default shard/realm
Remove all references to the default shard/realm from all tests that run as part of the gradle `hapiTestToken` task

### PR DESCRIPTION
**Pull request by JivkoKelchev**
**Description**:

Decouple `hapiTestToken` from default shard/realm.

**Related issue(s)**:

Fixes #18955

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java [hunk 1]
```diff
@@ -141,10 +141,8 @@ protected void assertExpectationsGiven(HapiSpec spec) throws Throwable {
                 || !absentRelationships.isEmpty()
                 || expectations.isPresent()
                 || registryEntry.isPresent()) {
-            final var detailsLookup = QueryVerbs.getAccountDetails(
-                            spec.setup().defaultShard().getShardNum() + "."
-                                    + spec.setup().defaultRealm().getRealmNum() + "."
-                                    + actualInfo.getContractID().getContractNum())
+            final var detailsLookup = QueryVerbs.getAccountDetails(spec.shard() + "." + spec.realm() + "."
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java:144]: Not a blocker, but is `getContractID` not sufficient?

```suggestion
            final var detailsLookup = QueryVerbs.getAccountDetails(actualInfo.getContractID());
```

**Review by mhess-swl — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java (hunk 1 above)
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java:144]: Yes, It is fixed in this [PR](https://github.com/hiero-ledger/hiero-consensus-node/pull/19077)
