### PR TITLE
test: HIP-904 negative cases for airdrops from contract

### LINKED ISSUE #16284: AIRDROP_FROM_CONTRACT_23
Contract airdrops a token with a custom fee (that should be paid by the sender) to an EOA receiver who is associated to the token and has receiverSigRequired=false. When the sender has NOT enough balance to pay the custom fee

Expected result: TokenAirdropTransaction should fail with error message:

### LINKED ISSUE #16285: AIRDROP_FROM_CONTRACT_24

### LINKED ISSUE #16286: AIRDROP_FROM_CONTRACT_25
Given a Contract sender airdrops maxLong of a token when the sender airdrops the same token again to the same receiver then the tokenAirdropTransaction should fail.

Expected result: TokenAirdropTransaction should fail with an error message:

### LINKED ISSUE #16287: AIRDROP_FROM_CONTRACT_26
Contract airdrops a token to themself

### LINKED ISSUE #16288: AIRDROP_FROM_CONTRACT_27
Contract account airdrops a token and while in pending we attempt to delete/selfdestruct the account.

Contract A has a balance of 10 FT A and has HBAR in balance.

1. Contract A signs a tokenAirdropTransaction for 1 FT A to Alice.

2. Contract A signs a cryptoDelete transaction/ selfdestruct

Expected result: 1. Successful tokenAirdropTransaction.
Alice = 1 pending airdrop for 1 FT A.

2. CryptoDelete/Selfdestruct should fail?

### PR DESCRIPTION
**Pull request by stoyanov-st**
**Description**:

Adding tests for cases Airdrop from contract 23, 24, 25, 26 and 27
**Related issue(s)**:

Fixes #16284 
Fixes #16285 
Fixes #16286 
Fixes #16287 
Fixes #16288 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropFromContractTest.java [hunk 1]
```diff
@@ -292,4 +309,206 @@ public Stream<DynamicTest> airdropToAccountWithFreeAutoAssocSlots(
...
+                                .sending(85_000_000L)
+                                .gas(1_500_000L)
+                                .via("AirdropTxn")
+                                .andAssert(txn -> txn.hasKnownStatuses(
+                                        CONTRACT_REVERT_EXECUTED, INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE)));
+            }));
+        }
+
+        @HapiTest
+        @DisplayName("Airdrop nft to the same account twice should fail with PENDING_NFT_AIRDROP_ALREADY_EXISTS")
```
Comment (lukelee-sl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropFromContractTest.java:349]: It seems like we test a few more things like "TOKEN_ID_REPEATED_IN_TOKEN_LIST"

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropFromContractTest.java [hunk 2]
```diff
@@ -292,4 +309,206 @@ public Stream<DynamicTest> airdropToAccountWithFreeAutoAssocSlots(
...
+                                .sending(85_000_000L)
+                                .gas(1_500_000L)
+                                .andAssert(txn -> txn.hasKnownStatuses(
+                                        CONTRACT_REVERT_EXECUTED, PENDING_NFT_AIRDROP_ALREADY_EXISTS)));
+            }));
+        }
+
+        @HapiTest
+        @DisplayName(
+                "Airdrop token amount of Long.MAX_VALUE then try to airdrop 1 more token to the same receiver should fail")
```
Comment (lukelee-sl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropFromContractTest.java:429]: Do we have a test for negative values somewhere?

**Review by lukelee-sl — APPROVED** [review]
Looks good overall.  Just a couple of questions

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropFromContractTest.java (hunk 1 above)
Comment (stoyanov-st) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropFromContractTest.java]: Adjusted the naming, also there are comments in the test describing what's happening there

**Review by lukelee-sl — APPROVED** [review]
LGTM
