### PR TITLE
fix: 18410: Bucket integrity check in HDHM.ReadUpdateBucketTask can be improved 

### LINKED ISSUE #18410: Bucket integrity check in HDHM.ReadUpdateBucketTask can be improved - release/0.61
This is a twin ticket for https://github.com/hiero-ledger/hiero-consensus-node/issues/18268 about forward porting this fix into release/0.61

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This is a cherry-pick of https://github.com/hiero-ledger/hiero-consensus-node/pull/18406

**Related issue(s)**:

Fixes #18410

### CODE REVIEW

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java [hunk 1]
```diff
@@ -609,8 +609,11 @@ protected boolean onExecute() throws IOException {
                 // Read from bytes
                 bucket.readFrom(bucketData);
                 if (bucketIndex != bucket.getBucketIndex()) {
-                    throw new RuntimeException(
+                    logger.warn(
```
Comment (OlegMazurov) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java:612]: We talked about making it an `error` if we want to keep the fix indefinitely.

**Review by anthony-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java]: Sure, makes sense. Fixed.

**Review by anthony-swirldslabs — APPROVED** [review]

**Review by OlegMazurov — DISMISSED** [review]

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java [hunk 2]
```diff
@@ -609,8 +609,11 @@ protected boolean onExecute() throws IOException {
                 // Read from bytes
                 bucket.readFrom(bucketData);
                 if (bucketIndex != bucket.getBucketIndex()) {
-                    throw new RuntimeException(
+                    logger.error(
+                            MERKLE_DB.getMarker(),
                             "Bucket index integrity check " + bucketIndex + " != " + bucket.getBucketIndex());
+                    bucket.clear();
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java:615]: Since it isn't just a temporary workaround for 0.59 any more, there should be some comments about what's going on here

Comment (anthony-swirldslabs) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java:620]: Minor: I'm unsure what `#18250` actually refers to. An issue? A pull request? Where? A complete URL would be a lot more helpful.

But thanks for the comment! It provides a great context.

**Review by anthony-swirldslabs — DISMISSED** [review]

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java (hunk 2 above)
Comment (anthony-swirldslabs) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java:622]: Thanks for adding the full URL! The fix looks perfect now.

**Review by anthony-swirldslabs — APPROVED** [review]
