### PR TITLE
fix: 18003 Fix version factory  in the test apps

### LINKED ISSUE #18003: JTR: `AddressBook-restart-upgrade-*` test failures
The following group of tests is failing in JTR tests suites

```
AddressBook-restart-upgrade-add-node-1k-4m
AddressBook-restart-upgrade-remove-node-1k-4m
AddressBook-restart-upgrade-weight-behavior2-1k-4m
```

There is nothing immediately obvious in the logs that would be the reason for the failure. 

@anthony-swirldslabs took a brief look and left the following comment:

> The test actually tries to compare AddressBook. It's just that with the migration to Rosters, certain fields in the AB stopped mattering for the platform, and they were difficult to generate/keep identical in the test for various reasons. So the test was modified to convert the ABs to Rosters, and then compare the resulting rosters instead of comparing the original ABs. Other than that, there's nothing Roster-specific in this failure.

> The roster basically contains nodeIds, weights, gossip keys, and gossip endpoints. So if there's a mismatch, it's a mismatch in these fields. There's not a whole lot of fixes since 2/7 that could potentially affect these parameters as seen at https://github.com/hiero-ledger/hiero-consensus-node/commits/main/ :
>- (very unlikely, but could skip a key) https://github.com/hiero-ledger/hiero-consensus-node/commit/fad43656b35bbf24225e66c2b62fdf30d036a7fc
>- (changes stakes logic, and hence potentially the weights) https://github.com/hiero-ledger/hiero-consensus-node/commit/894268da7108bea825418ae156f4a1aac0f05c5e
>- (probably unlikely) https://github.com/hiero-ledger/hiero-consensus-node/commit/222f26943615081b9334b17f6bf595b6c6499d40
there may be other relevant commits, but I cannot notice them or maybe I'm blind

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This PR fixes incorrect version factories for the test apps. Incorrectly produced versions ultimately cause tests failures. 

**Related issue(s)**:

Fixes #18003 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolStateLifecycles.java [hunk 1]
```diff
@@ -283,11 +283,21 @@ private boolean softwareUpgradeRemoveNodeWeightingBehavior1(
...
-                && equalsAsRoster(platformAddressBook, usedAddressBook, true)
-                && equalsAsRoster(platformAddressBook, updatedAddressBook, true)
-                && removedNodeFromAddressBook(platformAddressBook, stateAddressBook);
+        boolean platformVsConfig = equalsAsRoster(platformAddressBook, configAddressBook, true);
+        boolean platformVsState = equalsAsRoster(platformAddressBook, stateAddressBook, false);
+        boolean platformVsUsed = equalsAsRoster(platformAddressBook, usedAddressBook, true);
+        boolean platformVsUpdated = equalsAsRoster(platformAddressBook, updatedAddressBook, true);
+        boolean removedNode = removedNodeFromAddressBook(platformAddressBook, stateAddressBook);
+
+        logger.info(
```
Comment (mxtartaglia-sl) [inline platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolStateLifecycles.java:292]: Do we need this log info? How frequently will this be logged?

**Review by timo0 — APPROVED** [review]

**Review by mxtartaglia-sl — APPROVED** [review]

**Review by anthony-swirldslabs — APPROVED** [review]

**Review by edward-swirldslabs — APPROVED** [review]
