### PR TITLE
fix: Account deletion should release all alias forms

### LINKED ISSUE #15614: Account deletion should release all alias forms
### Description

Even though `CryptoCreateHandler` puts [two aliases](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java#L287) for the case of an ECDSA key alias, we see `TokenServiceApiImpl` removes at [most one alias](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java#L506).

This inconsistency doesn't really make sense.

### Steps to reproduce

As above.

### Additional context

_No response_

### Hedera network

_No response_

### Version

multiple

### Operating system

None

### PR DESCRIPTION
**Pull request by iwsimon**
**Description**:

**Related issue(s)**:

Fixes #15614 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java [hunk 1]
```diff
@@ -171,4 +181,44 @@ final Stream<DynamicTest> cannotDeleteTreasuryAccount() {
...
+                                                .setAccountID(AccountID.newBuilder()
+                                                        .setAlias(ByteString.copyFrom(explicitBytesOf(address))))
+                                                .setAmount(ONE_HUNDRED_HBARS)
+                                                .build())
+                                        .build()))
+                        .via("shouldBeAutoCreation")),
+                getTxnRecord("shouldBeAutoCreation")
+                        .andAllChildRecords()
+                        .hasNonStakingChildRecordCount(1)
+                        .logged());
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java:222]: It'd be nice to have one more op here that tries to access the account by its deleted alias (or aliases). Just a thought :)

**Review by mhess-swl — APPROVED** [review]

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java [hunk 2]
```diff
@@ -505,7 +508,15 @@ public void deleteAndTransfer(
         final var updatedDeleteAccount = requireNonNull(accountStore.get(deletedId));
         final var builder = updatedDeleteAccount.copyBuilder().deleted(true);
         if (freeAliasOnDeletion == YES) {
-            accountStore.removeAlias(updatedDeleteAccount.alias());
+            final var alias = updatedDeleteAccount.alias();
+            if (alias.length() > 0 && !isOfEvmAddressSize(alias)) {
+                final var key = asKeyFromAlias(alias);
+                final var evmAddress = extractEvmAddress(key);
+                if (evmAddress != null) {
+                    accountStore.removeAlias(evmAddress);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java:516]: It will be nice to have this check inside `removeAlias`

Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java]: Moved this to inside `removeAlias`

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java (hunk 1 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java:227]: Added one more op here.

File: hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableAccountStoreTest.java [hunk 3]
```diff
@@ -104,7 +104,7 @@ void canRemoveAlias() {
         writableStore.putAndIncrementCountAlias(alias.aliasOrThrow(), id);
         assertEquals(1, writableStore.sizeOfAliasesState());
         writableStore.removeAlias(alias.aliasOrThrow());
-        assertEquals(0, writableStore.sizeOfAliasesState());
+        assertEquals(-1, writableStore.sizeOfAliasesState());
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableAccountStoreTest.java:107]: Is this correct?

Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableAccountStoreTest.java:107]: Yes, this sizeOfAliasesState is really entityCounters.getCounterFor(EntityType.ALIAS). Since we moved the logic to removeAlias() as @Neeharika-Sompalli asked, with this alias, we decrease size 2.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java [hunk 4]
```diff
@@ -122,6 +125,14 @@ public void removeAlias(@NonNull final Bytes alias) {
         // We really shouldn't ever see an empty alias. But, if we do, we don't want to do any additional work.
         // FUTURE: It might be worth adding a log statement here if we see an empty alias, but maybe not.
         if (alias.length() > 0) {
+            if (!isOfEvmAddressSize(alias)) {
+                final var key = asKeyFromAlias(alias);
+                final var evmAddress = extractEvmAddress(key);
+                if (evmAddress != null) {
+                    aliases().remove(new ProtoBytes(evmAddress));
+                    entityCounters.decrementEntityTypeCounter(EntityType.ALIAS);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java:133]: Seemed not correct that we are decrementing twice here. But seems like we are incrementing twice in `CryptoCreateHandler`. So, this is correct.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @iwsimon

File: hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableAccountStoreTest.java (hunk 3 above)
Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableAccountStoreTest.java]: Removed.

**Review by lukelee-sl — APPROVED** [review]
LGTM

**Review by mhess-swl — APPROVED** [review]
