### PR TITLE
test: System files update test

### LINKED ISSUE #20836: Write new yahcli regression tests exercising all existing commands from the readme
Assume a `yahcli("<command line">)` operation exists---implement as a `NoOp` for now. See branch `20836-yahcli-reg-tests` for reference. 

- [x] Creating a new account - @tinker-michaelj 
- [ ] Updating system files - @JivkoKelchev 
- [x] Preparing for an NMT upgrade - @ibankov 
- [x] Launching an NMT telemetry upgrade - @ibankov 
- [ ] Scheduling a network freeze - @JivkoKelchev 
- [x] Re-keying an account - @ibankov 
- [x] Getting deployed version info of a network - @ibankov 
- [x] Creating a new key - @ibankov 
- [x] Printing key details - @ibankov 
- [x] Changing a staking election - @ibankov 
- [ ] Scheduling a transaction - @JivkoKelchev 
- [ ] Scheduling public key list update - @JivkoKelchev 
- [x] Activating staking after a network reset - @ibankov 
- [x] (DAB) Creating a node - @ibankov 
- [x] (DAB) Deleting a node - @ibankov 
- [x] (DAB) Updating a node - @ibankov 
- [ ] Add regression test PR check

### PR DESCRIPTION
**Pull request by JivkoKelchev**
**Description**:

Adds Yahcli regression tests for system files update command example.

**Related issue(s)**:

Fixes #20836

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/SystemFileCommandTest.java [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+                }));
+    }
+
+    // Helpers
+
+    private Path addressBookFilePath() {
+        return Path.of(DEFAULT_WORKING_DIR.get(), TEST_NETWORK, "sysfiles", "addressBook.json");
+    }
+
+    // add new entry in the address book
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/SystemFileCommandTest.java]: Is this the intended javadoc?

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/SystemFileCommandTest.java [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+                // upload updated file
+                yahcliSystemFile("upload", "address-book"),
+                // validate the new content
+                doingContextual(spec -> {
+                    allRunFor(
+                            spec,
+                            getFileContents(String.valueOf(fileNum))
+                                    .saveReadableTo(
+                                            serde::fromRawFile,
+                                            addressBookFilePath().toString()));
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/SystemFileCommandTest.java:63]: Since this test actually modifies the address book, even for a short period of time, we may want to use `@LeakyHapiTest`

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/SystemFileCommandTest.java (hunk 1 above)
Comment (JivkoKelchev) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/SystemFileCommandTest.java]: Removed.

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/regression/SystemFileCommandTest.java [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+import java.util.stream.Stream;
+import org.junit.jupiter.api.DynamicTest;
+import org.junit.jupiter.api.Order;
+import org.junit.jupiter.api.Tag;
+
+@Tag(REGRESSION)
+@OrderedInIsolation
+public class SystemFileCommandTest {
+
+    @Order(0)
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/regression/SystemFileCommandTest.java:40]: Is this needed if it's the only test in the class?

Doesn't need to block this PR, just curious

**Review by mhess-swl — DISMISSED** [review]
Looks good! Thanks @JivkoKelchev!

**Comment by mhess-swl** [comment]
@JivkoKelchev FYI the module info check is failing

**Review by andrewb1269hg — APPROVED** [review]
Approve the `build.gradle.kts` file.
