### PR TITLE
fix(17180): EventCreator ignores HealthMonitor update when squelching enabled 

### LINKED ISSUE #17180: Node 2 never returns to ACTIVE after reconnect in FCM-VM-MultiSBReconnect-3R-1k-20m JRS Test
Node 2 appears to not have its events chosen as parents by other nodes after it reconnects. 

JRS Data Folder: http://35.247.76.217:8095/swirlds-automation/release/0.58/10N/MultiSBReconnect/20241228-094044-GCP-Daily-MultiSBReconnect-3R-10N/FCM-VM-MultiSBReconnect-3R-1k-20m/

Node 2 did not reach ACTIVE state after reconnect (Node 2 logs) 
* 13m 53.138s - Reconnect completed and entered CHECKING state. 
* 13m 56.346s - init judges found. 
* 14m 3.196s - warning from Shadowgraph, missing non-expired self-parent. 
* 18m 33.903s - 22m 44.618s - repeated entries saying Copying round X, transactions ignored by expected map #. This log is added to debug #11254

[Looking at the stats pdf](http://35.247.76.217:8095/swirlds-automation/release/0.58/10N/MultiSBReconnect/20241228-094044-GCP-Daily-MultiSBReconnect-3R-10N/FCM-VM-MultiSBReconnect-3R-1k-20m/multipage_pdf.pdf), confirmed, node 2 remained in checking after reconnect/  
  * secC2C is maxed at 250 min after reconnect (indicating a self event never comes to consensus after reconnect). 
  * bufferedPriorityTransactions steadily climbs unbounded after the reconnect. 
  * TIPSET: Node 1 chose Node 2 as a pity parent near the reconnect, no other node chooses node 2 afterwards. 
  * TIPSET: Node 2 stops choosing pityparents for other nodes after the reconnect. 
  * secC2RC, secOR2T, secR2C all spike during the reconnect, but return to normal levels afterwards. 
  * secSc2T flatlines and twice the value of all other nodes after the reconnect. 
  * TIPSET: selfishness score flatlines at 0.1, less than half of all the other nodes. 
  * TIPSET: tipsetAdvancement flatlines at around 0.375, all other nodes are at 0.2 after reconnect. 
  * TIPSET: parentage selection of node2 by other nodes drops to 0 after reconnect and is never selected. 
  * cEvents_pre_second: node 2 drops to 0 after reconnect. 
  * eventCreation_fraction_OVERLOADED is maxed out at 1 for node 2.

### PR DESCRIPTION
**Pull request by mxtartaglia-sl**
**Description**:

When squelched, the EventCreator, if previously registered an unhealthy status by the health monitor, ignores the message that informs it that things are now in a healthy state again. Thus, it fails to start creating events again, given that the monitor doesn't repeat reports if they are unchanged.

 After this change, the monitor tracks the transitions to healthy and reports the healthy state repeatedly (even if unchanged) every 1 second.

**Related issue(s)**:

Fixes #17180

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by cody-littley — CHANGES_REQUESTED** [review]
This change introduces a race condition. The following conditions must be met in order to safely flush the wiring framework:

- no new data may be entering the system
- all cycles in the wiring graph must be broken. This is done by squelching.
- data flowing within the wiring diagram is now a DAG. Flush components in topological order.

I'm not sure if squelching is going to cause a bug since didn't do a deep dive on the reported issue. But I'm fairly confident that removing it is going to open the door for different bugs.

**Comment by mxtartaglia-sl** [comment]
Hey @cody-littley, thanks for the insight.  Truly appreciated.

background: Oleg's analysis exposed a situation where, after a reconnect, when squelching is enabled, the EventCreator, if previously registered from the health monitor an unhealthy duration, would ignore all incoming inputs, even the one that, from the health monitor, would inform that the platform is in a healthy status again, failing to start creating events once more.

> I'm not sure if squelching is going to cause a bug since I didn't do a deep dive on the reported issue. But I'm fairly confident that removing it is going to open the door for different bugs.

I see your point; I think that could happen if we completely remove the squelching feature (as is happening here [PR](https://github.com/hiero-ledger/hiero-consensus-node/pull/18358)). 

I am removing the squelching ONLY from the EventCreator in the current PR. 
The rationale is:
a) the eventcreator #maybeCreateEvent wire is already not emitting new events, given the platform status.
b) eventcreator # "health info" wire must accept input regardless of a reconnect being processed.
c)  eventcreator # "PlatformStatus" wire comes from the statusStateMachine, which was currently flushed before we used to enable squelching on the eventcreator component, so it would be ok to register the new input. 
d) eventcreator # "event window" is replaced in `ReconnectStateLoader#loadReconnectState()`
e) whatever happens with eventcreator # "PlatformEvent"  is later cleared using the "clear" wire.

The drawback is that it relies too much on how things work today.

> It would be WAY simpler and safer if things were simply discarded and reconstructed after a reconnect.

Agreed, although we are far from that to be possible,  other options that appeared are:
* The health monitor would report the duration even if it is unchanged, ensuring that the event creator would eventually receive the input when it stops squelching.
* Squelching is configurable per wire instead of per taskscheduler.

**Comment by netopyr** [comment]
I agree with Cody. Even if the fix would solve the observed issue, it would introduce much risk. `PlatformCoordinator.clear()` could never be used in any other scenario. Can we ensure this is the case and always will be?

**Comment by mxtartaglia-sl** [comment]
@netopyr  `PlatformCoordinator#clear` javadoc states:
```
    /**
     * Safely clears the system in preparation for reconnect. After this method is called, there should be no work
     * sitting in any of the wiring queues, and all internal data structures within wiring components that need to be
     * cleared to prepare for a reconnect should be cleared.
     */
```

I wouldn't say it was initially intended for any other use. 
That said, I'm all up for not introducing the indirect coupling and leaving the squelching (at least, if really not necessary) as documentation of the relationship. @lpetrovic05 any thoughts?

@netopyr, which of the alternatives would you prefer, if not this one?

A 3rd option proposed by Oleg is to have a different type of wire that would enable a direct modification of component's internal state from other tasksSchedulers belonging to connected components.

**Comment by lpetrovic05** [comment]
@cody-littley @mxtartaglia-sl @netopyr 
My thought is this. What Cody said about reconstructing is definitely the best and simplest approach, and this is what we plan to do. But in the meantime, we should probably fix this bug. This to me seems the simplest and safest approach to fixing this issue until we get around to rebuilding everything.

**Comment by cody-littley** [comment]
If I understand the issue correctly, the squelched component is accidentally squelching the message that informs it that things are now in a healthy state again?

If that's the case, a simple hack that wouldn't introduce new bugs would be to have the health monitor periodically send an "everything is good" message... perhaps once a second or so. Currently, it only sends that message when the status changes, but it wouldn't hurt anything to send it more frequently.

**Comment by mxtartaglia-sl** [comment]
@cody-littley correct, that is the issue.

**Comment by lpetrovic05** [comment]
> If I understand the issue correctly, the squelched component is accidentally squelching the message that informs it that things are now in a healthy state again?
> 
> If that's the case, a simple hack that wouldn't introduce new bugs would be to have the health monitor periodically send an "everything is good" message... perhaps once a second or so. (Note, this message probably shouldn't be sent while the node is reconnecting... don't want to clog up queues.) Currently, it only sends that message when the status changes, but it wouldn't hurt anything to send it more frequently.

We considered this approach, but we concluded that it will cause a lot more tasks to be created, which might have a performance impact. Because of this, we thought the current approach would be safer

**Comment by lpetrovic05** [comment]
> > It depends on the frequency. There are currently thousands, if not tens of thousands, of tasks flowing through the wiring framework each second. A few extra every second or two is unlikely to produce a measurable delta.
> 
> I agree with this.

Currently, the check is done 1000 times per second, there are 3 wires bound to its output. This is at least an additional 3000 tasks per second, I don't think this is insignificant.

@OlegMazurov  @poulok Thoughts on this?

**Comment by edward-swirldslabs** [comment]
> > > It depends on the frequency. There are currently thousands, if not tens of thousands, of tasks flowing through the wiring framework each second. A few extra every second or two is unlikely to produce a measurable delta.
> > 
> > 
> > I agree with this.
> 
> Currently, the check is done 1000 times per second, there are 3 wires bound to its output. This is at least an additional 3000 tasks per second, I don't think this is insignificant.
> 
> @OlegMazurov @poulok Thoughts on this?

Is a `task` something that is generating an item on a queue that has to be handled, or java byte code operating in to do a code branch test?

**Comment by mxtartaglia-sl** [comment]
> Is a task something that is generating an item on a queue that has to be handled
Depends on the scheduler type, but for most used cases, yes.

**Comment by lpetrovic05** [comment]
> > > > It depends on the frequency. There are currently thousands, if not tens of thousands, of tasks flowing through the wiring framework each second. A few extra every second or two is unlikely to produce a measurable delta.
> > > 
> > > 
> > > I agree with this.
> > 
> > 
> > Currently, the check is done 1000 times per second, there are 3 wires bound to its output. This is at least an additional 3000 tasks per second, I don't think this is insignificant.
> > @OlegMazurov @poulok Thoughts on this?
> 
> Is a `task` something that is generating an item on a queue that has to be handled, or java byte code executing to do a branch test?

It is an instance that is sent to the ForkJoinPool to be executed asynchronously. Its sort of like a queue, but not exactly.

**Comment by OlegMazurov** [comment]
> Currently, the check is done 1000 times per second, there are 3 wires bound to its output. This is at least an additional 3000 tasks per second, I don't think this is insignificant.

I believe we can afford that as a tentative solution (we have resources available even at high TPS).

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/internal/monitor/HealthMonitor.java [hunk 1]
```diff
@@ -71,6 +86,7 @@ public HealthMonitor(
 
         this.metrics = new HealthMonitorMetrics(metrics, healthLogThreshold);
         this.schedulers = new ArrayList<>();
+        this.healthyReportThreshold = Duration.ofSeconds(1);
```
Comment (timo0) [inline platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/internal/monitor/HealthMonitor.java:89]: should we have this configurable?

Comment (lpetrovic05) [reply platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/internal/monitor/HealthMonitor.java:89]: I would prefer that it is configurable, ideally with a `Duration`

**Review by lpetrovic05 — APPROVED** [review]

**Comment by mxtartaglia-sl** [comment]
@cody-littley your requested changes have been applied. Please review.

**Review by cody-littley — APPROVED** [review]
I didn't do a deep review, pressing the approve button to clear aware my previous "request changes" review.

**Review by timo0 — APPROVED** [review]
