### PR TITLE
fix: Fall back to `parseAndCheck()` if `parseSignedAndCheck()` is `INVALID_TX`

### LINKED ISSUE #20856: (0.65) Fallback to `Transaction` parsing for pre-upgrade PCES replay
After HIP-1127 in 0.65, the application submits serialized `SignedTransaction` messages to platform, but PCES may include `Transaction` messages serialized and submitted with 0.64.x software.

Although user txs from earlier releases are not applied to state, a `ParseException` is treated as a node due diligence failure; so we need to work around this to avoid charging node fee collections accounts for txs they submitted diligently right before the 0.65 upgrade.

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #20856 
    * Reproduces the scenario and verifies fix (including no `WARN` or `ERROR` logs) in a new `@RepeatableHapiTest` that temporarily switches to submitting with 0.64 message encoding.
 - 👉 This is a _0.65-only fix_, there is no corresponding PR to `main`.

### CODE REVIEW

**Review by jsync-swirlds — DISMISSED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java [hunk 1]
```diff
@@ -93,6 +95,14 @@ public TransactionResponse submit(
         return response;
     }
 
+    /**
+     * Causes the next transaction submitted to a non-default node to be encoded as
+     * a {@link Transaction} message, as before HIP-1127.
+     */
+    public void bypassNextWithPreHip1127TxFormat() {
```
Comment (artemananiev) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java:102]: Is it expected that this method is only called from test code?

**Review by derektriley — APPROVED** [review]
LGTM.

**Review by derektriley — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java (hunk 1 above)
Comment (mhess-swl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java:102]: Yes, this just notifies a target test network to simulate submitting a transaction in the old format. The only production codepath is in prehandle

**Review by mhess-swl — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/embedded/RepeatableEmbeddedHedera.java:102]: Yes this is in `test-clients` module @artemananiev

**Review by akdev — APPROVED** [review]
