### PR TITLE
fix: `hedera-addressbook-service-impl` unit tests due to different shard and realm

### LINKED ISSUE #17826: Run hedera-addressbook-service-impl unit tests with shard/realm different then 0/0 and fix errors

### PR DESCRIPTION
**Pull request by petreze**
**Description**:
Run all unit tests in `hedera-addressbook-service-impl` with different shard/realm values than `0` and fix all tests that failed. In this case, only `V053AddressBookSchemaTest` test class had some issues

**Related issue(s)**:

Fixes #17826 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V053AddressBookSchema.java [hunk 1]
```diff
@@ -151,7 +150,11 @@ private Key getAccountAdminKey(@NonNull final MigrationContext ctx) {
             log.info("AccountStore is not found, can be ignored.");
         }
         if (readableAccounts != null) {
+            final var hederaConfig = ctx.appConfig().getConfigData(HederaConfig.class);
+            final var accountConfig = ctx.appConfig().getConfigData(AccountsConfig.class);
             final var adminAccount = readableAccounts.get(AccountID.newBuilder()
+                    .shardNum(hederaConfig.shard())
+                    .realmNum(hederaConfig.realm())
                     .accountNum(accountConfig.addressBookAdmin())
```
Comment (ibankov) [inline hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V053AddressBookSchema.java:158]: I think this builder should be replaced with the Entity Factory once this [PR](https://github.com/hashgraph/hedera-services/pull/17822) is merged

**Review by thenswan — DISMISSED** [review]

**Review by ibankov — APPROVED** [review]

**Review by MiroslavGatsanoga — DISMISSED** [review]

File: hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/ids/EntityIdFactoryImpl.java [hunk 2]
```diff
@@ -57,4 +60,18 @@ public AccountID newAccountId(long number) {
                 .accountNum(number)
                 .build();
     }
+
+    @Override
+    public AccountID newAccountIdWithAlias(@NonNull Bytes alias) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/ids/EntityIdFactoryImpl.java:65]: We should probably rename this class to `FakeEntityIdFactoryImpl`. I was confused why we need both `EntityIdFactoryImpl` and `AppEntityIdFactory`

File: hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeSchemaRegistry.java [hunk 3]
```diff
@@ -140,7 +142,8 @@ public void migrate(
                     networkInfo,
                     nextEntityNum,
                     sharedValues,
-                    startupNetworks);
+                    startupNetworks,
+                    new AppEntityIdFactory(appConfig));
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeSchemaRegistry.java:146]: nit: We could use the fake version here ?

File: hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/ids/EntityIdFactoryImpl.java (hunk 2 above)
Comment (petreze) [reply hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/ids/EntityIdFactoryImpl.java:65]: Renamed

File: platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/lifecycle/EntityIdFactory.java [hunk 4]
```diff
@@ -14,12 +14,15 @@
  * limitations under the License.
  */
 
-package com.hedera.node.app.spi.ids;
+package com.swirlds.state.lifecycle;
```
[the remark this answers is not in the document]
Comment (petreze) [reply platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/lifecycle/EntityIdFactory.java:17]: The goal was to use use `AppEntityIdFactory` in `V053AddressBookSchema.migrate()` but I get circular dependency between
`... node.app.service.addressbook.impl` and `... node.app`. The other approach which I chose is to pass the `AppEntityIdFactory` through the `MigrationContext` but there is again circular dependency between `com.swirlds.state.api` and `com.hedera.node.app.spi` and this is why moved it in platform. However, I'm not sure if this is the proper place for it

[the remark this answers is not in the document]
Comment (Neeharika-Sompalli) [reply platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/lifecycle/EntityIdFactory.java:17]: Ah I see. We should add a `FUTURE` comment that this can be moved out once we have moved all migration code into `handle`.

**Review by Neeharika-Sompalli — APPROVED** [review]
Makes sense to me other than one comment that should be added. Thanks @petreze

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @petreze

File: platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/lifecycle/EntityIdFactory.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (petreze) [reply platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/lifecycle/EntityIdFactory.java:17]: Added, thanks a lot for the suggestion!

**Review by thenswan — APPROVED** [review]

**Review by vtronkov — APPROVED** [review]
