### PR TITLE
test: Fix PrecompileMintThrottlingCheck flake

### LINKED ISSUE #18866: PrecompileMintThrottlingCheck possible flake
It seems like the test is failing because the submitted ops are stuck in pending state and no transactions are throttled.

```
    2025-04-14 23:44:25.104 INFO   149  ProviderRun - 3 seconds left in test - 357 ops submitted so far (303 pending).
    2025-04-14 23:44:25.104 INFO   150  ProviderRun - Precheck txn status counts :: {OK=364}
    2025-04-14 23:44:25.105 INFO   151  ProviderRun - Resolved txn status counts :: {SUCCESS=53}
    2025-04-14 23:44:25.105 INFO   152  ProviderRun - 
    ------------------------------
    
    2025-04-14 23:44:26.132 INFO   149  ProviderRun - 2 seconds left in test - 408 ops submitted so far (345 pending).
    2025-04-14 23:44:26.133 INFO   150  ProviderRun - Precheck txn status counts :: {OK=[415](https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/14457582004/job/40544416464#step:33:416)}
    2025-04-14 23:44:26.133 INFO   151  ProviderRun - Resolved txn status counts :: {SUCCESS=62}
    2025-04-14 23:44:26.133 INFO   152  ProviderRun - 
    ------------------------------
    
    2025-04-14 23:44:27.132 INFO   149  ProviderRun - 1 seconds left in test - 459 ops submitted so far (387 pending).
    2025-04-14 23:44:27.132 INFO   150  ProviderRun - Precheck txn status counts :: {OK=466}
    2025-04-14 23:44:27.132 INFO   151  ProviderRun - Resolved txn status counts :: {SUCCESS=71}
    2025-04-14 23:44:27.132 INFO   152  ProviderRun - 
    ------------------------------
    
    2025-04-14 23:44:28.103 INFO   206  ProviderRun - Final breakdown of *provided* ops: {ContractCall=510}
    2025-04-14 23:44:28.103 INFO   207  ProviderRun - Final breakdown of *resolved* statuses: {SUCCESS=220}
    2025-04-14 23:44:28.132 WARN   224  HapiSpecOperation - 'PrecompileMintThrottlingCheck.precompileNftMintsAreLimitedByConsThrottle' - ProviderRun{} failed - Cannot invoke "java.util.concurrent.atomic.AtomicInteger.get()" because the return value of "java.util.EnumMap.get(Object)" is null!
    java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicInteger.get()" because the return value of "java.util.EnumMap.get(Object)" is null
    	at com.hedera.services.bdd.suites.throttling.PrecompileMintThrottlingCheck.lambda$precompileNftMintsAreLimitedByConsThrottle$0(PrecompileMintThrottlingCheck.java:82) ~[main/:?]
    	at com.hedera.services.bdd.spec.utilops.ProviderRun.lambda$submitOp$15(ProviderRun.java:209) ~[main/:?]
    	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
    	at com.hedera.services.bdd.spec.utilops.ProviderRun.submitOp(ProviderRun.java:209) ~[main/:?]
    	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:208) ~[main/:?]
    	at com.hedera.services.bdd.spec.HapiSpec.exec(HapiSpec.java:842) ~[main/:?]
    	at com.hedera.services.bdd.spec.HapiSpec.run(HapiSpec.java:641) ~[main/:?]
    	at com.hedera.services.bdd.spec.HapiSpec.execute(HapiSpec.java:606) ~[main/:?]
```

### PR DESCRIPTION
**Pull request by JivkoKelchev**
**Description**:

- Increase the number of max ops submitted, so there is a larger amount of throttled ops.
- Add wait for pending ops to finish, before the status count assertion.
- Fix NPE, when the count of the statuses is zero 

**Related issue(s)**:

Fixes #18866

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/ProviderRun.java [hunk 1]
```diff
@@ -193,12 +204,23 @@ protected boolean submitOp(HapiSpec spec) {
...
+        if (waitForPendingOps) {
+            if (!loggingOff) {
+                log.info("Waiting for {} pending ops to finish...", spec.numPendingOps());
+            }
+            long beginWait = Instant.now().toEpochMilli();
+            while (spec.numPendingOps() > 0
+                    || (Instant.now().toEpochMilli() - beginWait) < WAIT_PENDING_OPS_TIMEOUT.toMillis()) {
+                onSpinWait();
+            }
+        }
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/ProviderRun.java:222]: Is there nothing else we can trigger off of, instead of just waiting? Sometimes a spin loop is necessary, yes, but we try to avoid it unless absolutely needed

**Review by ibankov — APPROVED** [review]
LGTM!

**Review by vtronkov — APPROVED** [review]
