### PR TITLE
fix: Fix ISS reporting mechanism

### LINKED ISSUE #20304: Fix ISS reporting mechanism
**Description**
As has been pointed out in #20178 review, ISS logging data is not relevant: 

> Logging data from the current consensus state for an ISS is not correct. We can detect an ISS for states many rounds ago that have nothing to do with the consensus state. The state round number is in the round variable, whereas this line gets the state for the latest mutable round.
I suggest storing the state JSON string in the RoundHashValidator record in case there is an ISS and the information needs to be logged.

**What should be done**
Revisit ISS reporting and fix it, so that the investigation can be done as easily as possible.

### PR DESCRIPTION
**Pull request by thenswan**
Fixes  #20304 #20326

### CODE REVIEW

File: platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/legacy/payload/IssPayload.java [hunk 1]
```diff
@@ -112,7 +112,7 @@ public void setCatastrophic(final boolean catastrophic) {
      */
     @JsonRawValue
```
Comment (anthony-swirldslabs) [inline platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/legacy/payload/IssPayload.java]: W.r.t. https://github.com/hiero-ledger/hiero-consensus-node/pull/20355#discussion_r2231663408 ,

I think the root cause of this issue is at the line 113 here.

I don't necessarily suggest to modify this now because it's an old code. However, it would be nice to try and research this option while you're working on the fix because this annotation makes this method implementation very brittle. But again, I'm unsure why this was implemented this way in the first place. But I find the current code more complex than it needs to be.

Alternatively, if this is done on purpose because the value of this field represents an embedded (and quoted) JSON string (which by itself is a very-very-very poor design, but again, this is a legacy code), then the actual bug is in every method that returns an empty string for this value. Those return values should instead be replaced with `"\"\""` to actually return a **quoted** empty string so that it's actually a valid JSON string.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/DefaultIssDetector.java [hunk 2]
```diff
@@ -193,10 +185,11 @@ private IssNotification maybeCreateIssNotification(final long roundNumber, @NonN
      * force a decision on the hash, and handle any ISS events that result.
      *
      * @param roundNumber the round that was just completed
+     * @param stateJson the JSON string containing information about the current state
      * @return a list of ISS notifications, which may be empty, but will not contain null
      */
     @NonNull
-    private List<IssNotification> shiftRoundDataWindow(final long roundNumber) {
+    private List<IssNotification> shiftRoundDataWindow(final long roundNumber, @NonNull final String stateJson) {
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/DefaultIssDetector.java]: Had a discussion with @poulok, seems that we don't need this JSON at all. The same information is in the hashstream, so we don't need to duplicate it here.

Comment (thenswan) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/DefaultIssDetector.java]: @lpetrovic05 removed stateJson from the IssPayload

File: platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/legacy/payload/IssPayload.java (hunk 1 above)
Comment (thenswan) [reply platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/legacy/payload/IssPayload.java]: @anthony-swirldslabs we discussed this concept and decided to remove stateJson from the IssPayload ([see other conv](https://github.com/hiero-ledger/hiero-consensus-node/pull/20370#discussion_r2240230780))

**Review by poulok — APPROVED** [review]

File: platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/legacy/payload/IssPayload.java (hunk 1 above)
Comment (anthony-swirldslabs) [reply platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/legacy/payload/IssPayload.java]: Thanks. That works for me.
