### PR TITLE
fix: 19648 Introduced dedicated ForkJoin pool for hashing.

### LINKED ISSUE #19648: VirtualHasher runs hashing tasks in the common fork-join pool
This is a part of Virtual Mega Map (VMM) effort.

Here is code in `VirtualHasher`:

```java
        ForkJoinPool hashingPool = Thread.currentThread() instanceof ForkJoinWorkerThread thread
                ? thread.getPool()
                : ForkJoinPool.commonPool();
```

`hashingPool` is the thread pool where all hashing tasks are run. From the code above, if the current thread (where `VirtualHasher.hash()` is called) is already a fork-join thread, this thread's pool is used, otherwise the common pool. Before VMM, the current thread was a fork-join thread in the merkle tree hashing pool. Now this pool is gone, since there is no merkle tree hasher any longer. That's why virtual hashing is now running in the common pool, which is wrong.

This ticket is to run all virtual hashing tasks in a dedicated hashing pool.

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This PR introduces a dedicated fork-join pool for `VirtualHasher`

**Related issue(s)**:

Fixes #19648

### CODE REVIEW

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java [hunk 1]
```diff
@@ -336,10 +369,50 @@ public Hash hash(
                     };
         }
 
+        final VirtualHashListener listenerToUse = listener;
+
         ForkJoinPool hashingPool = Thread.currentThread() instanceof ForkJoinWorkerThread thread
```
Comment (OlegMazurov) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java]: Rename the local variable to not conflict with the field. Add explicit `final`?

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java [hunk 2]
```diff
@@ -336,10 +369,50 @@ public Hash hash(
...
+     * @return calculated root hash, or null if there are no dirty leaves to hash.
+     */
+    private Hash hashInternal(
+            final @NonNull LongFunction<Hash> hashReader,
+            final @NonNull Iterator<VirtualLeafBytes> sortedDirtyLeaves,
+            final long firstLeafPath,
+            final long lastLeafPath,
+            @Nullable VirtualHashListener listener,
+            final @NonNull VirtualMapConfig virtualMapConfig,
+            final @NonNull ForkJoinPool hashingPool) {
```
Comment (OlegMazurov) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java]: Rename the `hashingPool` parameter to not conflict with the field.

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java [hunk 3]
```diff
@@ -336,10 +369,50 @@ public Hash hash(
...
+     * @param virtualMapConfig platform configuration for VirtualMap
+     * @param hashingPool the pool to use for hashing tasks.
+     * @return calculated root hash, or null if there are no dirty leaves to hash.
+     */
+    private Hash hashInternal(
+            final @NonNull LongFunction<Hash> hashReader,
+            final @NonNull Iterator<VirtualLeafBytes> sortedDirtyLeaves,
+            final long firstLeafPath,
+            final long lastLeafPath,
+            @Nullable VirtualHashListener listener,
```
Comment (OlegMazurov) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java]: Should be `final @NonNull` or move the NoopListener here.

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java]: Fixed

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java (hunk 2 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java]: Fixed

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java (hunk 3 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java]: Fixed

Comment (OlegMazurov) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java]: Make it `@NonNull`

Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java]: Done

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/config/VirtualMapConfig.java [hunk 4]
```diff
@@ -127,6 +131,14 @@ public ConfigViolation virtualMapWarningThresholdValidation(final Configuration
         return null;
     }
 
+    public int getNumHashThreads() {
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/config/VirtualMapConfig.java:134]: With getNumHashThreads() properly implemented, I now wonder if default value "50.0" for `percentHashThreads` is good or should be increased?

Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/config/VirtualMapConfig.java:134]: I think we can answer this question once we have the load test results.
