### PR TITLE
fix: Ignore ID literals for individual input parameters

### LINKED ISSUE #19720: Handle ID literals as possible inputs
Shard/realm is configured with the target network in the yahcli config. But, it's still possible for input params – account numbers, node IDs, etc. – to be given as fully-qualified ID literals (e.g. `1.2.3` instead of just `3`). For a better user experience, Yahcli should normalize these inputs.

### PR DESCRIPTION
**Pull request by mhess-swl**
**Description**:
Yahcli configuration now supports configuring nonzero shard/realm via its config file, but it's still possible to cause unexpected behavior by specifying a fully-qualified entity ID as an input param (for many different commands). This PR accounts for possible ID literals by stripping said literals of their shard/realm, warning the end user with a console message, and falling back to the shard/realm in the configuration.

Also fixes:
* a bug that outputs the wrong shard/realm for a rekey operation
* a bug that outputs `NA` as the system file type for uploading/downloading system files 

Closes #19720

### CODE REVIEW

File: hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/util/ParseUtils.java [hunk 1]
```diff
@@ -29,4 +34,36 @@ public static SigControl keyTypeFromParam(final String keyType) {
...
+
+    /**
+     * Takes a string and, IF it is a fully-qualified entity ID, converts the ID to ONLY the third part.
+     * For any other values (including `null`), the value passed in will be the value returned.
+     * <p>
+     * E.g.:
+     * <li>
+     *     <ul>`1.2.3` will return `3`</ul>
+     *     <ul>`5` will return `5`</ul>
+     *     <ul>`null` will return `null`</ul>
```
Comment (timfn-hg) [inline hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/util/ParseUtils.java:51]: Is this for a string that is `"null"` or is this talking about an actual null object passed in? If its the latter, I think this would cause a NPE when `isIdLiteral(String)` is called because null gets passed to the pattern matcher which would conflict with the doc - or at least cause some confusion since it isn't super clear what `'null'` is.

File: hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/util/ParseUtils.java [hunk 2]
```diff
@@ -29,4 +34,36 @@ public static SigControl keyTypeFromParam(final String keyType) {
...
+     */
+    public static String normalizePossibleIdLiteral(ConfigManager config, String idLiteral) {
+        if (isIdLiteral(idLiteral)) {
+            final var entityIdParts = asDotDelimitedLongArray(idLiteral);
+            if (entityIdParts[0] != config.shard().getShardNum()
+                    || entityIdParts[1] != config.realm().getRealmNum()) {
+                mismatchedShardRealmMsg(config, Arrays.toString(entityIdParts));
+            }
+
+            return "" + entityIdParts[2];
```
Comment (timfn-hg) [inline hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/util/ParseUtils.java]: nit: `Long.toString(entityIdParts[2])`

File: hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/util/ParseUtils.java (hunk 1 above)
Comment (mhess-swl) [reply hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/util/ParseUtils.java:51]: Good catch! Fixed in the code and clarified in the documentation.

File: hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/util/ParseUtils.java (hunk 2 above)
Comment (mhess-swl) [reply hedera-node/test-clients/src/yahcli/java/com/hedera/services/yahcli/util/ParseUtils.java]: Done
