### PR TITLE
fix: 19748 Fixed `BreakableDataSource` lifecycle management for reconnect tests

### LINKED ISSUE #19748: `VirtualMapReconnectTest` fails with a memory allocation issue
`Timing Sensitive Unit Test` test suite (see https://github.com/hiero-ledger/hiero-consensus-node/runs/44246211667)
fails with the following issue:
```
 Check failure on line 0 in platform-sdk/swirlds-merkle/build/test-results/timingSensitive/TEST-com.swirlds.virtual.merkle.reconnect.VirtualMapReconnectTest.xml 

@github-actions
github-actions
/ Node: Timing Sensitive Unit Test Results
Error processing result file

Memory allocation failed : Huge input lookup, line 84347, column 64 (TEST-com.swirlds.virtual.merkle.reconnect.VirtualMapReconnectTest.xml, line 84347)
```

I suspect that the root cause is that some MerkleDB sources are not properly released. This issue is similar to what was fixed https://github.com/hiero-ledger/hiero-consensus-node/pull/19318

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This PR makes sure that instances `BreakableDataSource` instances get released. If not done properly, it may cause OOM errors. 

**Related issue(s)**:

Fixes #19748 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/BrokenBuilder.java [hunk 1]
```diff
@@ -22,6 +24,8 @@ public final class BrokenBuilder implements VirtualDataSourceBuilder {
     volatile int numCalls = 0;
     volatile int numTimesBroken = 0;
 
+    static volatile Set<VirtualDataSource> COPIES_TO_DESTROY = ConcurrentHashMap.newKeySet();
```
Comment (anthony-swirldslabs) [inline platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/BrokenBuilder.java]: `private final`. Also, please remove `volatile`.

File: platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/BrokenBuilder.java [hunk 2]
```diff
@@ -90,4 +98,14 @@ public void setNumTimesToBreak(final int numTimesToBreak) {
...
+
+    public static void closeDatasourceCopies() {
+        COPIES_TO_DESTROY.forEach(v -> {
+            try {
+                v.close();
+            } catch (IOException e) {
+                throw new RuntimeException(e);
+            }
+        });
+    }
```
Comment (anthony-swirldslabs) [inline platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/BrokenBuilder.java]: Given that the set is static, should this code remove items from the set once they're closed?

Comment (imalygin) [reply platform-sdk/swirlds-merkle/src/timingSensitive/java/com/swirlds/virtual/merkle/reconnect/BrokenBuilder.java]: yes, fair enoungh
