### PR TITLE
fix: HIP-632 fix alias length check

### LINKED ISSUE #17570: fix: reported issues with HIP-632 alias<->account conversions
Have report of problems with alias<->account view functions.

See [branch here](https://github.com/hashgraph/hedera-smart-contracts/tree/getEvmAddressAliasPublic-failure) which
has tests that show a particular use of the two view methods returns the wrong answer.

### PR DESCRIPTION
**Pull request by stoyanov-st**
**Description**:
This PR fixed a behaviour that was checking whether the alias is 20 bytes long.
Now it uses a helper method from `AliasUtils` to verify and extract the given alias

**Related issue(s)**:

Fixes #17570 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/getevmaddressalias/EvmAddressAliasCall.java [hunk 1]
```diff
@@ -53,11 +54,12 @@ public EvmAddressAliasCall(@NonNull final HasCallAttempt attempt, final Address
         }
 
         // If the account does not have an evm address as an alias
-        if (account.alias().length() != 20) {
+        final var evmAlias = AliasUtils.extractEvmAddress(account.alias());
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/getevmaddressalias/EvmAddressAliasCall.java:57]: I see that this calls the static method `asKeyFromAliasOrElse`.  It is hard to tell if this is what was causing the issue.  Were you able to validate that @quiet-node test was fixed by this change?

Comment (stoyanov-st) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/getevmaddressalias/EvmAddressAliasCall.java:57]: I used the exact same test in order to debug the issue. The said account in the test had an ECDSA derived alias that is expected to work as per HIP-583 (correct me here if I'm wrong) and return the corresponding EVM address.

**Review by lukelee-sl — APPROVED** [review]
LGTM
