### PR TITLE
fix: Marks nodes deleted if not present in `override-network.json`

### LINKED ISSUE #19824: Possible bug in application logic of `override-network.json`
The contents of the `override-network.json` file is meant to be the complete set of nodes in the address book/roster to adopt on the network. It is not simply a set of nodes that need some values in the state overwritten. Everything about the address book in the state should be ignored when applying the `override-network.json`.

Example:, The address book in state has node A, B, and C. The `override-network.json` has nodes A, B, and D. The address book on startup should only have nodes A, B, and D.

[Slack Convo](https://swirldslabs.slack.com/archives/C08SW2A136K/p1750187598768249?thread_ts=1749670456.459819&cid=C08SW2A136K)

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fixes #19824 

- Marks the nodes that are present in the state and not in the `override-network.json` as deleted.

### CODE REVIEW

File: hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java [hunk 1]
```diff
@@ -44,15 +42,32 @@ default void restart(@NonNull final MigrationContext ctx) {
...
                 .forEach(node -> {
+                    final var id = new EntityNumber(node.nodeId());
                     adoptedNodeCount.getAndIncrement();
-                    nodes.put(new EntityNumber(node.nodeId()), node);
+                    liveNodeIds.add(id);
+                    nodes.put(id, node);
                 });
+        log.info("Adopted nodes {} from startup assets (override-network.json)", liveNodeIds);
+
+        nodes.keys().forEachRemaining(nodeId -> {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java]: I should probably be not using `keys()` here. But I thought this is only used in test environments. What do you think @tinker-michaelj ?

Comment (mhess-swl) [reply hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java]: This does imply that `keys()` is acceptable for use in other production code, which we probably don't want to encourage. It's easy enough to compute the set of remaining node IDs. 

I also wonder if solo networks ever need to use an override network, though I can't think of a legitimate example...

Just my 2 cents.

File: hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java [hunk 2]
```diff
@@ -44,15 +42,32 @@ default void restart(@NonNull final MigrationContext ctx) {
...
+            final var node = requireNonNull(nodes.get(nodeId));
+            if (!liveNodeIds.contains(nodeId)) {
+                nodes.put(
+                        new EntityNumber(nodeId.number()),
+                        node.copyBuilder().deleted(true).build());
```
Comment (mhess-swl) [inline hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java]: The ticket states that an override network should _completely_ replace the existing address book. If an existing node isn't in the override file, should we be removing it entirely (instead of only marking it as deleted)? A future nodeUpdate transaction could bring the deleted node back to life, which seems contrary to the idea of complete replacement

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java]: We don't remove any node from state currently. It can be done safely only after this ticket is complete https://github.com/hiero-ledger/hiero-consensus-node/issues/18855. Since the override-networks is only used in testing, marking the nodes as deleted should set the weight to 0.

File: hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java]: As discussed, will move this to use dispatches instead of mutating state directly.

File: hapi/hedera-protobuf-java-api/src/main/proto/services/state/roster/roster_state.proto [hunk 3]
```diff
@@ -33,6 +33,18 @@ message RosterState {
...
+      * Indicates whether the roster transplant is in progress.<br/>
+      * This is needed to determine if all the node creations and deletions are complete.
+      * True while a transplant roster is still being processed (nodes are
+      * being created/updated/deleted).  Reset to false once dispatch is finished.
+      *
+      * <p>
+      * A transplant roster is one that has been adopted from another network
+      * using an override startup asset, rather than being generated by the current network's consensus.
+     */
+    bool transplant_in_progress = 3;
```
Comment (poulok) [inline hapi/hedera-protobuf-java-api/src/main/proto/services/state/roster/roster_state.proto:47]: Is this truly needed? It seems a shame to put something in the state that only supports a non-production use case.

Comment (Neeharika-Sompalli) [reply hapi/hedera-protobuf-java-api/src/main/proto/services/state/roster/roster_state.proto:47]: The previous approach was changing state directly in schema, which we are trying to avoid for block streams. Since it is a non production use case, we gave an exception. But to fix the bug I have to use `KVState.keys()` in the schema that will be **extremely slow** with Mega map.
To avoid that, I had to follow the pattern we use to change state in `HandleWorkflow` instead of modifying state in schema. In this approach, if we don't have this field in state, there will have a high risk of ISS in all these testing environments. 
I am not sure which approach is the best.

File: hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java]: > It's easy enough to compute the set of remaining node IDs.

@mhess-swl  We need entityCounts to know set of remaining node Ids. But we don't have a way to say entityId service will migrate first and read all the counts. So, we don't know the set of nodeIds here if we follow same approach.

Comment (mhess-swl) [reply hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java]: The entity ID service used to migrate first. It used to be a requirement. Is that not the case anymore?

**Review by poulok — APPROVED** [review]
LGTM, but as discussed, it is worth checking with the users of this feature to determine if the benefit is worth adding a non-production field into the state.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 4]
```diff
@@ -260,6 +260,19 @@ public void handleRound(
         recordCache.resetRoundReceipts();
         boolean transactionsDispatched = false;
 
+        try {
+            // This is only set if streamMode is BLOCKS or BOTH or once user transactions are handled
+            // Dispatch transplant updates for the nodes in override network
+            if (boundaryStateChangeListener.lastConsensusTime() != null) {
```
Comment (tinker-michaelj) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: I think it's more explicit to use `if (streamMode != RECORDS)` and just accept a `RECORDS`-only network will not support override networks after release `0.64`.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 5]
```diff
@@ -260,6 +260,19 @@ public void handleRound(
...
+                transactionsDispatched |= systemTransactions.dispatchTransplantUpdates(
+                        state,
+                        boundaryStateChangeListener.lastConsensusTimeOrThrow().plusNanos(1),
```
Comment (tinker-michaelj) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: I'm still a little concerned that if there are lots of DAB transactions required, their consensus times could collide with the first platform-assigned consensus time in some edge cases.

Maybe we should increase [this property](https://github.com/hiero-ledger/hiero-consensus-node/blob/main/hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java#L534) to like `scheduling.reservedSystemTxnNanos=100`? This should cover any realistic size of a test environment.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 6]
```diff
@@ -260,6 +260,19 @@ public void handleRound(
         recordCache.resetRoundReceipts();
         boolean transactionsDispatched = false;
 
+        try {
+            // This is only set if streamMode is BLOCKS or BOTH or once user transactions are handled
+            // Dispatch transplant updates for the nodes in override network
+            if (boundaryStateChangeListener.lastConsensusTime() != null) {
+                transactionsDispatched |= systemTransactions.dispatchTransplantUpdates(
```
Comment (tinker-michaelj) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: ⚠️ This is _always_ creating a new `SystemContext`, `ReadableStoreFactory`, `ReadableRosterStore`, `ReadableNodeStore`, and checking the file system for an override network.

I suggest instead we,
  1. Add a mutable field to `HandleWorkflow`, `boolean checkedForTransplant = false`.
  2. If `!checkedForTransplant`, explicitly here (once) create the necessary `ReadableRosterStore` to see if a transplant is in progress (if so, `dispatchTransplantUpdates()`), and set `checkedForTransplant = true`. 

This way it's obvious that any JVM will check on disk for a transplant at most once.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java [hunk 7]
```diff
@@ -134,6 +146,7 @@ public class SystemTransactions {
     private final ExchangeRateManager exchangeRateManager;
     private final HederaRecordCache recordCache;
     private final SemanticVersion softwareVersionFactory;
```
Comment (derektriley) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java]: This field is unused, and looks like it can be removed.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java [hunk 8]
```diff
@@ -463,6 +478,86 @@ public void dispatchNodeRewards(
...
+                                            .serviceEndpoint(node.serviceEndpoint())
+                                            .declineReward(node.declineReward())
+                                            .grpcProxyEndpoint(node.grpcProxyEndpoint())
+                                            .build())
+                                    .build(),
+                            node.nodeId());
+                    log.info("Node {} is new in override network and is being created", node.nodeId());
+                } else {
+                    // Node is in the override roster and in current state, dispatch a node update transaction
+                    systemContext.dispatchAdmin(b -> b.memo("Synthetic node update")
```
Comment (derektriley) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java:512]: Was thinking about this, would we ever have values in the `override-network.json` for a node that would fail in `preHandle` of the `NodeUpdateHandler` but we actually want it to be updated (like `accountId` if `updateAccountIdAllowed` is false? for example). Or are we just accepting the limitation/behavior that the contents will be dispatched and must obey the current config?

File: hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/AddressBookTransplantSchema.java]: yeah that hack is removed in one of the cleanups Michael did

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 4 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: I used this because we are doing same check in other places to recognize `streamMode != RECORDS`. Would you like me to change it everywhere ?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java (hunk 7 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java]: Yes removed. Thanks @derektriley

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java (hunk 8 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java:512]: Oh yeah, it should obey current config. I think we will test with the config that will be enabled in production. Since this is only used in test networks, we should be fine.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 6 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: yeah makes sense Michael.. fixed it. Thanks!

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 5 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: Does this not conflict with the purging schedules ?

Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: It does reduce the number of consensus times available for executing long-term scheduled transactions, but that is not currently a bottleneck.

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: Changed the property. Thanks @tinker-michaelj

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 4 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: Left it as `boundaryStateChangeListener.lastConsensusTime() != null` similar to other conditions, as discussed

**Review by poulok — APPROVED** [review]
