### PR TITLE
fix: Decouple hapiTestSmartContracts shard and realm

### LINKED ISSUE #18957: Decouple `hapiTestSmartContract` from default shard/realm
Remove all references to the default shard/realm from all tests that run as part of the gradle `hapiTestSmartContract` task

### PR DESCRIPTION
**Pull request by JivkoKelchev**
**Description**:

Removes all references to the default shard/realm from all tests that run as part of the gradle `hapiTestSmartContract` task

**Related issue(s)**:

Fixes #18957

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiPropertySource.java [hunk 1]
```diff
@@ -278,11 +278,11 @@ static AccountID asAccount(long shard, long realm, long num) {
                 .build();
     }
 
-    static ContractID asContract(String shard, String realm, String num) {
+    static ContractID asContract(long shard, long realm, long num) {
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiPropertySource.java:281]: Let's create an overload instead of changing this method. We have enough strings getting parsed throughout the hapi test classes that it's probably worth keeping both. Same for `asTokenId(...)` below.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java [hunk 2]
```diff
@@ -265,13 +262,15 @@ final Stream<DynamicTest> disallowCreationsOfEmptyInitCode() {
...
-                contractCreate(contract).balance(666),
-                contractCall(contract, "donate", donationArgs).hasKnownStatus(CONTRACT_REVERT_EXECUTED));
+        return hapiTest(uploadInitCode(contract), contractCreate(contract).balance(666), withOpContext((spec, log) -> {
+            Object[] donationArgs = new Object[] {
+                new BigInteger(HapiPropertySource.asSolidityAddress((int) spec.shard(), spec.realm(), 666666L)),
+                "Hey, Ma!"
+            };
+            final var callOp = contractCall(contract, "donate", donationArgs).hasKnownStatus(CONTRACT_REVERT_EXECUTED);
+            allRunFor(spec, callOp);
+        }));
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java:273]: Weird formatting here.. if spotless didn't do this (and allows it), the extra lines help it read much easier like it was before

```
return hapiTest(
            uploadInitCode(...
            contractCreate(...
            contractCall(...
            // etc.
```

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java [hunk 3]
```diff
@@ -591,22 +590,32 @@ final Stream<DynamicTest> delegateContractIdRequiredForTransferInDelegateCall()
...
+                withOpContext((spec, logger) -> {
+                    final var callOP = contractCall(
+                            sendInternalAndDelegateContract,
+                            "sendRepeatedlyTo",
+                            new BigInteger(HapiPropertySource.asSolidityAddress(
+                                    (int) spec.shard(), spec.realm(), justSendContractNum.get())),
+                            new BigInteger(HapiPropertySource.asSolidityAddress(
+                                    (int) spec.shard(), spec.realm(), beneficiaryAccountNum.get())),
+                            BigInteger.valueOf(totalToSend / 2));
+                    allRunFor(spec, callOP);
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java:602]: I've been toying with the idea of putting shard/realm into each `Op` since they seems to be needed so often (but not in all cases). No need to change anything here, but curious what your thoughts are?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java [hunk 4]
```diff
@@ -1238,8 +1239,11 @@ final Stream<DynamicTest> twoComplexKeysRequired() {
     @HapiTest
     final Stream<DynamicTest> specialAccountsBalanceCheck() {
         return hapiTest(IntStream.concat(IntStream.range(1, 101), IntStream.range(900, 1001))
-                .mapToObj(i -> getAccountBalance(String.format("%s.%s.%s", shard, realm, i))
-                        .logged())
+                .mapToObj(i -> withOpContext((spec, log) -> {
+                    final var balanceOp = getAccountBalance(String.format("%s.%s.%s", spec.shard(), spec.realm(), i))
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java:1243]:
```suggestion
                    final var balanceOp = getAccountBalance(asEntityString(spec.shard(), spec.realm(), i))
```

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CreatePrecompileSuite.java [hunk 5]
```diff
@@ -652,20 +602,18 @@ final Stream<DynamicTest> createTokenWithDefaultExpiryAndEmptyKeys() {
...
+                contractCall(TOKEN_CREATE_CONTRACT, tokenCreateContractAsKeyDelegate)
+                        .via(FIRST_CREATE_TXN)
+                        .gas(GAS_TO_OFFER)
+                        .sending(DEFAULT_AMOUNT_TO_SEND)
+                        .payingWith(ACCOUNT)
+                        .exposingResultTo(result -> {
+                            log.info(EXPLICIT_CREATE_RESULT, result[0]);
+                            final var res = (Address) result[0];
+                            createdTokenNum.set(numberOfLongZero(
+                                    HexFormat.of().parseHex(res.toString().substring(2))));
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CreatePrecompileSuite.java:614]: I recognize you're only moving what's already there, but since this code is changing anyway:
```suggestion
                                    // Remove the leading '0x'
                                    HexFormat.of().parseHex(res.toString().substring(2))));
```

**Review by mhess-swl — APPROVED** [review]
Whew, a ton of work! Tyvm @JivkoKelchev! 

My comments are all nits–feel free to address them here or in a separate PR. Thanks again! 🙏

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/leaky/LeakyContractTestsSuite.java [hunk 6]
```diff
@@ -1035,9 +1029,8 @@ final Stream<DynamicTest> whitelistNegativeCases() {
         final AtomicLong whitelistedCalleeMirrorNum = new AtomicLong();
         final AtomicReference<TokenID> tokenID = new AtomicReference<>();
         final AtomicReference<String> attackerMirrorAddr = new AtomicReference<>();
-        final AtomicReference<String> unListedCalleeMirrorAddr = new AtomicReference<>();
-        final AtomicReference<String> whitelistedCalleeMirrorAddr = new AtomicReference<>();
-
+        final AtomicReference<byte[]> unListedCalleeMirrorAddr = new AtomicReference<>();
```
[the remark this answers is not in the document]
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/leaky/LeakyContractTestsSuite.java:1032]: We are setting `unListedCalleeMirrorAddr.set(asSolidityAddress(id)` which is `byte[]` solidity address representation.

In my opinion, there were too many conversions, that were not needed. So I’m introducing a new `HapiContractCreate` method - `exposingContractIdTo`.
Instead of exposing the created contract num, it exposes the ID, so there is no need to build it with the **default shard and realm**. Then we can populate the EVM address byte array (without creating the hexed string) and store it in the atomic variable for using it to call the contract.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java [hunk 7]
```diff
@@ -413,19 +416,20 @@ private HapiSpecOperation[] createOpsArray(
...
+            opsArray[i] = contractCall(contract, methodName, mirrorAddrParamFunction(accounts.get(index)))
                     .hasKnownStatus(status);
         }
         return opsArray;
     }
 
-    private @NonNull String getNthNextEntityFrom(final long nth, final long from) {
-        return SHARD_AND_REALM + (from + nth);
+    private @NonNull String getNthNextEntityFrom(final long nth, final ContractID fromId) {
+        return String.format("%d.%d.%d", fromId.getShardNum(), fromId.getRealmNum(), fromId.getContractNum() + nth);
```
[the remark this answers is not in the document]
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java]: Fixed

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java [hunk 8]
```diff
@@ -473,7 +471,8 @@ final Stream<DynamicTest> hapiTransferFromForNFTWithInvalidAddressesFails() {
                                                 asAddress(spec.registry().getTokenID(NFT_TOKEN))),
                                         HapiParserUtil.asHeadlongAddress(
                                                 asAddress(spec.registry().getAccountID(OWNER))),
-                                        HapiParserUtil.asHeadlongAddress(NON_EXISTING_ADDRESS),
+                                        HapiParserUtil.asHeadlongAddress(
+                                                asSolidityAddress((int) spec.shard(), spec.realm(), 123456)),
```
[the remark this answers is not in the document]
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java]: Sure, fixed. 
I know it shouldn't be upper case, but all other variables in this test are, and I don't want more changes in this PR.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/BaseErroringAssertsProvider.java [hunk 9]
```diff
@@ -35,8 +36,12 @@ protected void registerProvider(AssertUtils.ThrowingAssert throwing) {
     @SuppressWarnings("unchecked")
     protected <R> void registerIdLookupAssert(String key, Function<T, R> getActual, Class<R> cls, String err) {
         registerProvider((spec, o) -> {
-            R expected =
-                    isIdLiteral(key) ? parseIdByType(key, cls) : spec.registry().getId(key, cls);
+            final var keyToUse = isNumericLiteral(key)
+                    ? String.format("%d.%d.%d", spec.shard(), spec.realm(), Long.parseLong(key))
```
[the remark this answers is not in the document]
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/BaseErroringAssertsProvider.java]: Fixed

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java (hunk 2 above)
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java:273]: Hmm, spotless keeps putting these ops on one line 😅

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiPropertySource.java (hunk 1 above)
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiPropertySource.java:297]: I notice that the most string variants are not even used.
But, I guess you are right, it doesn't hurt if we keep the both.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java (hunk 3 above)
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java:602]: There are already shard and realm in the spec, and we use them while creating the body of transactions and queries. Which is sufficient for most of the `Ops`.

For smart contracts `Op`s however, we are expecting parameters to be passed from outside the op/spec context. 
In that case, we are building all kinds of addresses and IDs statically. 
I’m not sure if it is possible to avoid `withOpContext` or `@FunctionalInterface` fields, like this one in `HapiContractCall` `private Optional<Function<HapiSpec, Object[]>> paramsFn = Optional.empty();`

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/leaky/LeakyContractTestsSuite.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (mhess-swl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/leaky/LeakyContractTestsSuite.java:1032]: > In my opinion, there were too many conversions

Agreed. I tried this same thing yesterday–using `byte[]` instead of `ByteString`–and it worked well. Thanks for explaining!

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (mhess-swl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java]: Can easily fix later, no problem

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java (hunk 3 above)
Comment (mhess-swl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java:602]: Yeah maybe not. Just seems like we shouldn't have to pass around shard and realm so much 🤔 oh well, thanks for the thought
