### PR TITLE
fix: detach FCQueue copy when serializing

### LINKED ISSUE #11086: Java heap OOM in the teacher during reconnect
### Description

The reconnect connection gets broken due to a problem on the learner side. After a while, the teacher dies with OOM.

### Steps to reproduce

The issue was observed with a single-node mode reconnect testing framework. It needs to be investigated further to see if the issue may affect networks.

### Additional context

The OOM is due to not releasing an FCQueue for expirable transaction records.
See also #11364

### Hedera network

other

### Version

v0.47.0-SNAPSHOT

### Operating system

Linux

### PR DESCRIPTION
**Pull request by OlegMazurov**
**Description**:
We serialize `FCQueue` when saving a state or during reconnect. A detached copy ensures the shared linked list of nodes can be garbage collected upon release of subsequent `FCQueue` copies.

**Related issue(s)**:

Fixes #11086

**Notes for reviewers**:
* Also removed support for version 2 serialization.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-fcqueue/src/main/java/com/swirlds/fcqueue/FCQueue.java [hunk 1]
```diff
@@ -741,41 +741,46 @@ public int hashCode() {
...
+        Node<E> dst = new Node<>();
+        head = dst;
+        while (src != tail) {
+            dst.element = src.element;
+            dst.runningHash = src.runningHash;
+            dst.next = new Node<>();
+            src = src.next;
+            dst = dst.next;
+        }
+        dst.runningHash = src.runningHash;
```
Comment (artemananiev) [inline platform-sdk/swirlds-fcqueue/src/main/java/com/swirlds/fcqueue/FCQueue.java:774]: Why is this needed? `dst` points to the tail at this point

**Review by artemananiev — APPROVED** [review]
