### PR TITLE
fix: Remove Deprecated Gas Calculator

### LINKED ISSUE #15098: [SMALL] Remove flags and the deprecated code after the integrity of the fix for gas precision and view operation gas is verified.
### Problem

This [PR](https://github.com/hashgraph/hedera-services/pull/14842) fixes issue #10828 which results in different gas values for the same operation, when exchange rate for the network is different.

### Solution

Remove `isGasPrecisionLossFixEnabled` and `isCanonicalViewGasEnabled` flags and the Deprecated code, after the integrity of the fix for gas precision is verified. This will happen after its verified on test environments.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by stoyanov-st**
**Description**:
This PR removes the deprecated methods for gas calculation, tiny bars conversion and adjusts the related tests

**Related issue(s)**:

Fixes #15098 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/gas/SystemContractGasCalculatorTest.java [hunk 1]
```diff
@@ -37,14 +37,13 @@ void setUp() {
 
     @Test
     void returnsMinimumGasCostForViews() {
-        assertEquals(100L, subject.viewGasRequirement());
+        assertEquals(1198L, subject.viewGasRequirement());
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/gas/SystemContractGasCalculatorTest.java:40]: This is expected, correct?  Was the feature flag set in such a way as to return the 100 gas previously?

**Review by lukelee-sl — APPROVED** [review]
LGTM
